### ISSUE TITLE
Loader Not Displaying on Page Load 

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#1]
Description: The loader does not appear when the page is loaded. The intended preloader animation is missing, causing the website to skip the loading screen.

Steps to Reproduce:

Open the website.
Observe that the loader is not visible when the page is loading.
Expected Behavior: The loader should be visible for 2-3 seconds when the page is loading, providing feedback to the user.

Actual Behavior: The loader is not shown at all, and the page loads without any loading animation.
![Screenshot 2024-09-17 145019](https://github.com/user-attachments/assets/88d769ba-a474-4d5e-abbc-9c3b80f5e484)

**Comment by ujjwal006** [comment]
i have fixed the issue

**Comment by Priya-rai121** [comment]
@NishantSinghhhhh 

> Expected Behavior: The loader should be visible for 2-3 seconds when the page is loading, providing feedback to the user.

Wouldn't it be better if the loading animation is displayed until the contents of the website have loaded instead of a hardcoded time duration (of 2-3 seconds).

I have fixed the issue and made a PR implementing this feature.

**Comment by ashum9** [comment]
i have fixed the issue

**Comment by amar641** [comment]
I have fixed the issue.
