### ISSUE TITLE
Navigation Button Not Working Nav Open

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#2]
Nav Open Button (Issue with nav-open-btn):
Expected Behavior: The nav-open-btn should allow users to open the navigation bar when clicked, displaying the menu options.
Actual Behavior: Clicking on the nav-open-btn does not open the navigation bar, rendering the menu inaccessible.

Possible Cause: The data-nav-toggler attribute for the nav-open-button is not connected to an event listener, making the button non-functional.

![Screenshot 2024-09-17 150140](https://github.com/user-attachments/assets/919fa95a-93a4-4a56-b21b-259346225680)

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by ujjwal006** [comment]
I have fixed the issue

**Comment by Priya-rai121** [comment]
I have fixed the issue!

**Comment by ashum9** [comment]
i have fixed the issue
