### ISSUE TITLE
Navigation Buttons Not Working Close

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#3]
Close Button (Issue with close-button):
Expected Behavior: The close-button should close the navigation menu when clicked, hiding the menu.

Actual Behavior: The close-button does not respond to clicks, leaving the navigation bar open and preventing the user from closing it.

Possible Cause: Similar to the nav-open-button, the data-nav-toggler for the close-button lacks an event listener, causing the button to be inactive.
![Screenshot 2024-09-17 150743](https://github.com/user-attachments/assets/2886cf5c-c8c7-40d3-8f4a-322c7c4d3ac7)

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by ujjwal006** [comment]
I have fixed this issue

**Comment by ashum9** [comment]
i have fixed the issue
