### ISSUE TITLE
Issue: Update Website Data 

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#30]
Description:

The website contains outdated information that needs to be refreshed to enhance user experience and accuracy.

Changes Needed:

Text Content:

Update homepage product descriptions.
Revise the "About Us" section with recent achievements.
![Screenshot 2024-09-25 212515](https://github.com/user-attachments/assets/5c3c2973-caed-46e1-a3c8-81d3f3ec9004)

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by ashum9** [comment]
i have fixed the issue
