### ISSUE TITLE
Add Hover effect for Image 

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#36]
Current Hover effect:

https://github.com/user-attachments/assets/a02c141d-efd7-4406-9437-449bb4523d7f

Expected Hover Effect:

https://github.com/user-attachments/assets/745dc509-6cba-45d9-9400-d4402226c8ae

**Comment by Shashwat-Trivedi** [comment]
I have Fixed this issue

**Comment by justbeingashutosh** [comment]
I have fixed this issue. The following image shows my implementation.
![Screenshot_20241003_194223-1](https://github.com/user-attachments/assets/a4505544-ea9a-47cb-b4da-eae1a59d1953)
