### ISSUE TITLE
Improving the UI Of the menu section

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#37]
Current Behaviour: 

https://github.com/user-attachments/assets/6e3c6c9f-22c8-41d7-9e8a-12d33ddb4aea

Expected Behavior:

You need to replicate the hover effect where two lines appear below each navigation item upon hovering. This effect will enhance the visual appeal and interactivity of the navigation menu.

Hover Effect: On hover, two lines should animate below each nav item.
The first line should appear, followed by the second line.
Ensure the lines are styled to complement the overall design of the website.
Expected Outcome:

This hover effect will provide users with clear feedback, improving navigation and user engagement on the site.

Expected Hover Effect
https://github.com/user-attachments/assets/c82cf51a-84a3-49b3-aa86-587baceae741

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by ujjwal006** [comment]
I have fixed this issue
