### ISSUE TITLE
Issue: Open Outlook When Clicking on Email Addresses

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#38]
We need to ensure that when a user clicks on any email address on the website, it automatically opens Outlook with a new email draft addressed to the selected email.

What Needs to Be Done:

When an email address is clicked, it should trigger the user's default mail client (Outlook) and open a new email draft with the email address pre-filled.
Ensure compatibility with all major browsers and devices.
Expected Outcome:

Clicking on any email address should seamlessly open Outlook, allowing users to quickly send emails without manually copying the address.

Current Behavior:

https://github.com/user-attachments/assets/ec94544f-7cb0-42be-a42e-9c6e505914d6

Expected Behavior:

https://github.com/user-attachments/assets/d046b955-46b1-4d8a-ae16-dfda25360b0b

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by ashum9** [comment]
i have fixed the issue
