### ISSUE TITLE
Issue: Add Cart Icon in Navbar with Functionality to Add/Remove Items from Cart

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#56]
Description:
We need to implement a cart icon in the navbar that dynamically updates the number of items in the cart based on user interaction with the Add to Cart and Remove from Cart buttons in the dishes menu. The icon should initially display a number 0, indicating the cart is empty. Users will be able to add or remove dishes from the cart, and the number in the cart icon will increase or decrease accordingly.

Expected Features:

1. Cart Icon in Navbar:
   - Display a cart icon in the navbar.
   - The icon should have a number next to it, starting with 0.
   - This number represents the total count of items in the cart.

2. Add/Remove from Cart Button:
   - Each dish in the menu section should have an Add to Cart button.
   - After clicking Add to Cart, the button should change to Remove from Cart.
   - When Remove from Cart is clicked, the button should revert to Add to Cart.

3. Cart Count Functionality:
   - When a dish is added to the cart, the number in the cart icon should increase.
   - When a dish is removed from the cart, the number in the cart icon should decrease.
   - The count should accurately reflect the number of unique items in the cart.

4. Use Cases to Consider:
   - Multiple items can be added and removed without any bugs or errors.
   - Ensure the cart count doesn’t go below 0.
   - Handle edge cases where the user tries to add or remove the same dish multiple times.
   - Ensure the state is properly managed across all pages/components where cart functionality is used.

Implementation:
- Update the navbar to include the cart icon and number indicator.
- Modify the menu section to include an Add to Cart button for each dish.
- Write the necessary JavaScript or React logic to handle the state changes when items are added or removed from the cart.
- Ensure the solution is bug-free and handles all the possible interactions a user might have with the Add to Cart and Remove from Cart buttons.

Acceptance Criteria:
- The cart icon in the navbar should correctly show the total number of items added to the cart.
- Buttons for each dish should toggle between Add to Cart and Remove from Cart based on user actions.
- The cart count should accurately update without any bugs or glitches, and the overall experience should be smooth and intuitive.

**Comment by justbeingashutosh** [comment]
I have fixed this issue. 
![Screenshot_20241002_114935](https://github.com/user-attachments/assets/fb301baf-3979-44b3-a1f2-5c18137ce8a0)

**Comment by krafcik02** [comment]
Hello, I'd like to try and work on this, can you assign me this issue? :)
