### ISSUE TITLE
Issue: Implement Blog Section with Blog Submission Form and Rendering Feature

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#71]
Description: We need to create a new Blog Section on the website that allows users to submit their blogs through a form. The form should collect the user's name, email, and description of the blog. Once the user submits the blog using the Submit Blog button, the blog should render immediately below the form, displaying the entered details.

Expected Features:

Blog Section:

A new section should be added to the website dedicated to blogs.
This section will display a form for submitting a blog and render submitted blogs underneath.
Blog Submission Form:

The form should include the following fields:
Name: Text input field for the user's name.
Email: Text input field for the user's email address.
Description: A text area for the blog content.
A Submit Blog button should be included for submitting the blog.
Render Blog Below:

Once the blog is submitted, it should be rendered below the form.
The rendered blog should display the name, email, and blog description in a neat, readable format.
Each new blog should append to the list of previously submitted blogs.
Form Validation:

Ensure that the name, email, and description fields are properly validated before submission.
The email field should accept only valid email formats.
If any required field is missing or invalid, appropriate error messages should be displayed.
User Experience:

The form and rendered blogs should be well-styled and consistent with the overall website design.
The user should see a confirmation or success message after successfully submitting a blog.

**Comment by justbeingashutosh** [comment]
I have fixed this issue. Please note that i have fixed both issue #71 and #72 in a single PR since they were related. The following image shows my implementation:
![Screenshot_20241003_172835](https://github.com/user-attachments/assets/e30758fe-37d8-4d00-b2a8-dd5ba2e8948a)
