### ISSUE TITLE
Issue: Improve the UI of the Blog Page to Match the Website Design

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#72]
Description: The UI of the Blog Page needs to be enhanced to align with the overall design and aesthetics of the website. The styling of the blog submission form, as well as the rendered blogs, should be consistent with the website's theme to provide a seamless user experience.

Expected Features:

Consistent Design:

The blog page should adopt the same color scheme, typography, and layout used across the website.
Ensure that all UI components on the blog page (form, buttons, text fields, etc.) match the styles of the website.

Blog Submission Form UI:
The form should be visually appealing and fit well with the website’s design.
Proper padding, margins, and alignment should be applied to the form fields.
The Submit Blog button should be styled to match the buttons used elsewhere on the site.

Rendered Blogs:
Each rendered blog should have a clean and readable layout that fits with the site’s overall look.
Ensure proper spacing between the blogs, consistent font sizes, and alignment.
Add subtle styling for visual distinction, such as borders or background color, if necessary.

Responsiveness:
Ensure that the blog page is fully responsive, with the UI adapting properly to different screen sizes.
Maintain a good user experience on both desktop and mobile devices.

User Experience:
The UI should be intuitive and easy to use, ensuring that the blog page feels like an integrated part of the overall website.

**Comment by justbeingashutosh** [comment]
I have fixed this issue. Please note that i have fixed both issue https://github.com/FSOC-OSS/FSOC.V3/issues/71 and https://github.com/FSOC-OSS/FSOC.V3/issues/72 in a single PR since they were related. The following image shows my implementation: 
![Screenshot_20241003_172835](https://github.com/user-attachments/assets/503a1449-1207-4e30-9c90-53cf9fbb786b)

**Comment by ujjwal006** [comment]
I have fixed this issue.
![image](https://github.com/user-attachments/assets/bc4f1ed9-b418-4c1e-8dd9-cce5bd597443)

**Comment by ujjwal006** [comment]
I have fixed this issue.
![image](https://github.com/user-attachments/assets/5c251567-84f8-4c59-8902-a416590b0d3a)
