### ISSUE TITLE
 Issue: Add Links to Footer Section Using JavaScript 

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#73]
We need to dynamically add links to the footer section of the website using JavaScript to ensure easier maintenance and flexibility.

What Needs to Be Done: Use JavaScript to create and insert links into the footer section.

![Screenshot 2024-09-26 005721](https://github.com/user-attachments/assets/fe60d1e9-cf93-44c2-b96c-c94d62d8301b)

**Comment by justbeingashutosh** [comment]
I have fixed this issue.

**Comment by ujjwal006** [comment]
I have fixed this issue.
