### ISSUE TITLE
Issue: Add Login Option in Navbar with Validation and Password Strength Check

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#85]
Description:
Feature Request: Add a login option in the navbar.
Functionality:
When the login option is clicked, a new page should open displaying a login form.
The form should contain two fields:
Email
Password
Below the fields, there should be a submit button.
Form Validation Requirements:
Email Validation:

Ensure the email entered is in the correct format (e.g., example@example.com).
If the email format is incorrect, a toast message should be displayed instructing the user to enter a valid email.
Password Validation:

On clicking the submit button, the strength of the password must be checked (e.g., length, special characters, etc.).
If the password is too weak, provide appropriate feedback (e.g., a message or toast).
Acceptance Criteria:
A login option is present in the navbar.
A new page opens with a login form on clicking the login option.
The form validates the email and displays a toast for incorrect formats.
The password strength is checked on submission, and the user is informed if the password is too weak.

**Comment by justbeingashutosh** [comment]
I have fixed this issue. Below is my implementation.
![Screenshot_20241004_180432](https://github.com/user-attachments/assets/30d463e9-0fc6-47af-b471-696e43dc436c)
