### ISSUE TITLE
Issue: Add "Book a Table" Button in Hero Section with Table Reservation Form

### ISSUE THREAD

**Issue by NishantSinghhhhh** [FSOC-OSS/FSOC.V3#88]
Description:
Feature Request: There is a "Book a Table" button in the hero section.

Functionality:
On clicking the "Book a Table" button, a new page should open with a table reservation form.

Reservation Form Requirements:
The form should collect the following information:
Preferred Dining Time
Number of Seats
Estimated Cost:

After entering the required information, the form should display an estimated cost that the person would need to pay. The cost can be generated randomly for simplicity.

Acceptance Criteria:
The "Book a Table" button is present in the hero section.
Clicking the "Book a Table" button opens a new page with a reservation form.
The form collects the dining time and number of seats.
An estimated cost (randomly generated) is displayed based on the input.

![Screenshot 2024-10-03 203754](https://github.com/user-attachments/assets/436d6c9b-2030-4a75-97a3-8dbe3e743e34)

**Comment by justbeingashutosh** [comment]
I have fixed this issue
